### PR TITLE
Updated to Bevy 0.13

### PR DESCRIPTION
**Pull request by sardap**

### CODE REVIEW

**Review by bakcxoj — APPROVED** [review]

**Comment by martinlindhe** [comment]
Additional changes for bevy 0.14 can be found here: https://github.com/sardap/bevy_video/compare/main...martinlindhe:bevy_video:deps 

It is based on this PR.

**Comment by bakcxoj** [comment]
I didn't realize people were actually using this crate. Just made it on a whim for a project I was working on.

**Comment by bakcxoj** [comment]
@martinlindhe If I merge this PR, would you make another PR that puts us on Bevy 0.14?

**Comment by sardap** [comment]
Glad this got merged thank you!

**Comment by martinlindhe** [comment]
> @martinlindhe If I merge this PR, would you make another PR that puts us on Bevy 0.14?

Sure! Incoming soon.

**Pull request merged**
